# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/beronthecolossus/Peki/C++/Projects/OK/MathEval

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/beronthecolossus/Peki/C++/Projects/OK/MathEval

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/beronthecolossus/Peki/C++/Projects/OK/MathEval/CMakeFiles /home/beronthecolossus/Peki/C++/Projects/OK/MathEval/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/beronthecolossus/Peki/C++/Projects/OK/MathEval/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MathEval

# Build rule for target.
MathEval: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MathEval
.PHONY : MathEval

# fast build rule for target.
MathEval/fast:
	$(MAKE) -f CMakeFiles/MathEval.dir/build.make CMakeFiles/MathEval.dir/build
.PHONY : MathEval/fast

#=============================================================================
# Target rules for targets named Parser

# Build rule for target.
Parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Parser
.PHONY : Parser

# fast build rule for target.
Parser/fast:
	$(MAKE) -f CMakeFiles/Parser.dir/build.make CMakeFiles/Parser.dir/build
.PHONY : Parser/fast

#=============================================================================
# Target rules for targets named BinaryExpression

# Build rule for target.
BinaryExpression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BinaryExpression
.PHONY : BinaryExpression

# fast build rule for target.
BinaryExpression/fast:
	$(MAKE) -f CMakeFiles/BinaryExpression.dir/build.make CMakeFiles/BinaryExpression.dir/build
.PHONY : BinaryExpression/fast

#=============================================================================
# Target rules for targets named NumberExpression

# Build rule for target.
NumberExpression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NumberExpression
.PHONY : NumberExpression

# fast build rule for target.
NumberExpression/fast:
	$(MAKE) -f CMakeFiles/NumberExpression.dir/build.make CMakeFiles/NumberExpression.dir/build
.PHONY : NumberExpression/fast

#=============================================================================
# Target rules for targets named Token

# Build rule for target.
Token: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Token
.PHONY : Token

# fast build rule for target.
Token/fast:
	$(MAKE) -f CMakeFiles/Token.dir/build.make CMakeFiles/Token.dir/build
.PHONY : Token/fast

#=============================================================================
# Target rules for targets named TokenNode

# Build rule for target.
TokenNode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TokenNode
.PHONY : TokenNode

# fast build rule for target.
TokenNode/fast:
	$(MAKE) -f CMakeFiles/TokenNode.dir/build.make CMakeFiles/TokenNode.dir/build
.PHONY : TokenNode/fast

#=============================================================================
# Target rules for targets named Lexer

# Build rule for target.
Lexer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Lexer
.PHONY : Lexer

# fast build rule for target.
Lexer/fast:
	$(MAKE) -f CMakeFiles/Lexer.dir/build.make CMakeFiles/Lexer.dir/build
.PHONY : Lexer/fast

#=============================================================================
# Target rules for targets named Expression

# Build rule for target.
Expression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Expression
.PHONY : Expression

# fast build rule for target.
Expression/fast:
	$(MAKE) -f CMakeFiles/Expression.dir/build.make CMakeFiles/Expression.dir/build
.PHONY : Expression/fast

BinaryExpression.o: BinaryExpression.cpp.o

.PHONY : BinaryExpression.o

# target to build an object file
BinaryExpression.cpp.o:
	$(MAKE) -f CMakeFiles/BinaryExpression.dir/build.make CMakeFiles/BinaryExpression.dir/BinaryExpression.cpp.o
.PHONY : BinaryExpression.cpp.o

BinaryExpression.i: BinaryExpression.cpp.i

.PHONY : BinaryExpression.i

# target to preprocess a source file
BinaryExpression.cpp.i:
	$(MAKE) -f CMakeFiles/BinaryExpression.dir/build.make CMakeFiles/BinaryExpression.dir/BinaryExpression.cpp.i
.PHONY : BinaryExpression.cpp.i

BinaryExpression.s: BinaryExpression.cpp.s

.PHONY : BinaryExpression.s

# target to generate assembly for a file
BinaryExpression.cpp.s:
	$(MAKE) -f CMakeFiles/BinaryExpression.dir/build.make CMakeFiles/BinaryExpression.dir/BinaryExpression.cpp.s
.PHONY : BinaryExpression.cpp.s

Expression.o: Expression.cpp.o

.PHONY : Expression.o

# target to build an object file
Expression.cpp.o:
	$(MAKE) -f CMakeFiles/Expression.dir/build.make CMakeFiles/Expression.dir/Expression.cpp.o
.PHONY : Expression.cpp.o

Expression.i: Expression.cpp.i

.PHONY : Expression.i

# target to preprocess a source file
Expression.cpp.i:
	$(MAKE) -f CMakeFiles/Expression.dir/build.make CMakeFiles/Expression.dir/Expression.cpp.i
.PHONY : Expression.cpp.i

Expression.s: Expression.cpp.s

.PHONY : Expression.s

# target to generate assembly for a file
Expression.cpp.s:
	$(MAKE) -f CMakeFiles/Expression.dir/build.make CMakeFiles/Expression.dir/Expression.cpp.s
.PHONY : Expression.cpp.s

Lexer.o: Lexer.cpp.o

.PHONY : Lexer.o

# target to build an object file
Lexer.cpp.o:
	$(MAKE) -f CMakeFiles/Lexer.dir/build.make CMakeFiles/Lexer.dir/Lexer.cpp.o
.PHONY : Lexer.cpp.o

Lexer.i: Lexer.cpp.i

.PHONY : Lexer.i

# target to preprocess a source file
Lexer.cpp.i:
	$(MAKE) -f CMakeFiles/Lexer.dir/build.make CMakeFiles/Lexer.dir/Lexer.cpp.i
.PHONY : Lexer.cpp.i

Lexer.s: Lexer.cpp.s

.PHONY : Lexer.s

# target to generate assembly for a file
Lexer.cpp.s:
	$(MAKE) -f CMakeFiles/Lexer.dir/build.make CMakeFiles/Lexer.dir/Lexer.cpp.s
.PHONY : Lexer.cpp.s

NumberExpression.o: NumberExpression.cpp.o

.PHONY : NumberExpression.o

# target to build an object file
NumberExpression.cpp.o:
	$(MAKE) -f CMakeFiles/NumberExpression.dir/build.make CMakeFiles/NumberExpression.dir/NumberExpression.cpp.o
.PHONY : NumberExpression.cpp.o

NumberExpression.i: NumberExpression.cpp.i

.PHONY : NumberExpression.i

# target to preprocess a source file
NumberExpression.cpp.i:
	$(MAKE) -f CMakeFiles/NumberExpression.dir/build.make CMakeFiles/NumberExpression.dir/NumberExpression.cpp.i
.PHONY : NumberExpression.cpp.i

NumberExpression.s: NumberExpression.cpp.s

.PHONY : NumberExpression.s

# target to generate assembly for a file
NumberExpression.cpp.s:
	$(MAKE) -f CMakeFiles/NumberExpression.dir/build.make CMakeFiles/NumberExpression.dir/NumberExpression.cpp.s
.PHONY : NumberExpression.cpp.s

Parser.o: Parser.cpp.o

.PHONY : Parser.o

# target to build an object file
Parser.cpp.o:
	$(MAKE) -f CMakeFiles/Parser.dir/build.make CMakeFiles/Parser.dir/Parser.cpp.o
.PHONY : Parser.cpp.o

Parser.i: Parser.cpp.i

.PHONY : Parser.i

# target to preprocess a source file
Parser.cpp.i:
	$(MAKE) -f CMakeFiles/Parser.dir/build.make CMakeFiles/Parser.dir/Parser.cpp.i
.PHONY : Parser.cpp.i

Parser.s: Parser.cpp.s

.PHONY : Parser.s

# target to generate assembly for a file
Parser.cpp.s:
	$(MAKE) -f CMakeFiles/Parser.dir/build.make CMakeFiles/Parser.dir/Parser.cpp.s
.PHONY : Parser.cpp.s

Token.o: Token.cpp.o

.PHONY : Token.o

# target to build an object file
Token.cpp.o:
	$(MAKE) -f CMakeFiles/Token.dir/build.make CMakeFiles/Token.dir/Token.cpp.o
.PHONY : Token.cpp.o

Token.i: Token.cpp.i

.PHONY : Token.i

# target to preprocess a source file
Token.cpp.i:
	$(MAKE) -f CMakeFiles/Token.dir/build.make CMakeFiles/Token.dir/Token.cpp.i
.PHONY : Token.cpp.i

Token.s: Token.cpp.s

.PHONY : Token.s

# target to generate assembly for a file
Token.cpp.s:
	$(MAKE) -f CMakeFiles/Token.dir/build.make CMakeFiles/Token.dir/Token.cpp.s
.PHONY : Token.cpp.s

TokenNode.o: TokenNode.cpp.o

.PHONY : TokenNode.o

# target to build an object file
TokenNode.cpp.o:
	$(MAKE) -f CMakeFiles/TokenNode.dir/build.make CMakeFiles/TokenNode.dir/TokenNode.cpp.o
.PHONY : TokenNode.cpp.o

TokenNode.i: TokenNode.cpp.i

.PHONY : TokenNode.i

# target to preprocess a source file
TokenNode.cpp.i:
	$(MAKE) -f CMakeFiles/TokenNode.dir/build.make CMakeFiles/TokenNode.dir/TokenNode.cpp.i
.PHONY : TokenNode.cpp.i

TokenNode.s: TokenNode.cpp.s

.PHONY : TokenNode.s

# target to generate assembly for a file
TokenNode.cpp.s:
	$(MAKE) -f CMakeFiles/TokenNode.dir/build.make CMakeFiles/TokenNode.dir/TokenNode.cpp.s
.PHONY : TokenNode.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/MathEval.dir/build.make CMakeFiles/MathEval.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/MathEval.dir/build.make CMakeFiles/MathEval.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/MathEval.dir/build.make CMakeFiles/MathEval.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... MathEval"
	@echo "... Parser"
	@echo "... BinaryExpression"
	@echo "... NumberExpression"
	@echo "... Token"
	@echo "... TokenNode"
	@echo "... Lexer"
	@echo "... Expression"
	@echo "... BinaryExpression.o"
	@echo "... BinaryExpression.i"
	@echo "... BinaryExpression.s"
	@echo "... Expression.o"
	@echo "... Expression.i"
	@echo "... Expression.s"
	@echo "... Lexer.o"
	@echo "... Lexer.i"
	@echo "... Lexer.s"
	@echo "... NumberExpression.o"
	@echo "... NumberExpression.i"
	@echo "... NumberExpression.s"
	@echo "... Parser.o"
	@echo "... Parser.i"
	@echo "... Parser.s"
	@echo "... Token.o"
	@echo "... Token.i"
	@echo "... Token.s"
	@echo "... TokenNode.o"
	@echo "... TokenNode.i"
	@echo "... TokenNode.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

